trigger:
- master

resources:
- repo: self

variables:
  IMAGE_NAME: 'alpine'
  tag: '$(Build.BuildId)'

stages:
- stage: "Build DockerHub Images"
  jobs:
  - job: "docker"
    strategy:
      matrix:
        amd64-alpine:
          IMAGE_SUFF: glib
          IMAGE_TAG: 10.3.1
        amd64-alpine-glibc:
          IMAGE_SUFF: miniglib
          IMAGE_TAG: 10.3.1
        amd64-alpine-glibc-miniconda:
          IMAGE_TAG: minicondaglib
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
