# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageName: 'alpine'
  tag: '$(Build.BuildId)'
  dockerHubImageName: 'wallaskrea/$(imageName)'
  acrRegistryName: 'gomods'
  acrLoginServer: '$(acrRegistryName).azurecr.io'
  acrImageName: '$(acrLoginServer)/$(imageName)'

stages:
- stage: "Build DockerHub Images"
  jobs:
  - job: "docker"
    strategy:
      matrix:
        amd64-alpine:
          IMAGE_SUFF: glib
          IMAGE_TAG: 10.3.1
        amd64-alpine-glibc:
          IMAGE_SUFF: mini
          IMAGE_TAG: 10.3.1
        amd64-alpine-glibc-miniconda:
          IMAGE_TAG: miniglib
    pool:
      vmImage: 'win1803'
    steps:
    - powershell: |
        choco install azure-cli
        gci 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin'
        echo "docker build"
        docker build --isolation=hyperv -f Dockerfile.$(imageName)${IMAGE_SUFF} -t $(imageName) .
        echo "dockerhub login"
        docker login -u $(dockerHubUsername) -p $(dockerHubPassword)
        echo "tag for dockerhub"
        docker tag $(dockerHubImageName) $(imageName)
        echo "push to dockerhub"
        docker push $(dockerHubImageName)
        # echo "done with dockerhub and ACR push"
        # for some reason choco install azure-cli does not add the az dir to the PATH
        # dir based on https://github.com/Azure/azure-cli/blob/dev/build_scripts/windows/Product.wxs
        #echo "Azure CLI Login"
        #& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u $(acr-appId) -p $(acr-password) --tenant $(acr-tenant)
        #echo "ACR login"
        #& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" acr login --name $(acrRegistryName)
        #echo "tag for ACR"
        #docker tag $(imageName) $(acrImageName)
        #docker push $(acrImageName)    
        #echo "done with ACR push"