trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to wkreaDockerHub
      inputs:
        containerRegistry: 'wkreaDockerHub'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'wkreaDockerHub'
        repository: 'test'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Alpine/Dockerfile.AlpineGLIB'
        arguments: -t $(containerRegistry)/Alpine$(Build.Repository.Name)
    - task: Docker@2
      inputs:
        containerRegistry: 'wkreaDockerHub'
        repository: 'test'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: Logout of wkreaDockerHub
      inputs:
        containerRegistry: 'wkreaDockerHub'
        command: 'logout'