# trigger:
# - master
trigger:
  branches:
    include:
      - refs/tags/{tagname}
    exclude:
      - refs/tags/{othertagname}
# specific path build
pr:
  branches:
    include:
    - releases/*
    exclude:
    - master
  paths:
    include:
    - docs/*
    exclude:
    - docs/README.md

resources:
- repo: self

pool:
  vmImage: 'Ubuntu-18.04'

variables:
- name: imageName
  value: 'alpinemini:$(build.buildId)'

steps:
- task: Docker@2
  displayName: Login to wkreaDockerHub
  inputs:
    containerRegistry: 'wkreaDockerHub'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'wkreaDockerHub'
    command: 'build'
    Dockerfile: $(Build.SourcesDirectory)/Alpine/Dockerfile.AlpineMini
- task: Docker@2
  inputs:
    containerRegistry: 'wkreaDockerHub'
    repository: 'alpinemini'
    command: 'push'
    tags: |
      $(Build.BuildId)
      latest
- script: |
    docker build -f $(Build.SourcesDirectory)/Alpine/Dockerfile.alpinemini -t wallaskrea/$(imageName) .
    docker tag wallaskrea/$(imageName) wallaskrea/$(imageName)
    docker push wallaskrea/$(imageName)
  displayName: 'docker build'