trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '{{ containerRegistryConnection.Id }}'
  imageRepository: '{{#toAlphaNumericString imageRepository 50}}{{/toAlphaNumericString}}'
  containerRegistry: '{{ containerRegistryConnection.Authorization.Parameters.loginServer }}'
  dockerfilePath: '{{ dockerfilePath }}'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to wkreaDockerHub
      inputs:
        containerRegistry: 'wkreaDockerHub'
        command: 'login'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'wkreaDockerHub'
        repository: 'test'
        command: build
        Dockerfile: '$(Build.SourcesDirectory)/Alpine/Dockerfile.AlpineGLIB'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'wkreaDockerHub'
        repository: 'test'
        command: push
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: Logout of wkreaDockerHub
      inputs:
        containerRegistry: 'wkreaDockerHub'
        command: 'logout'