# For test containers
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml#multiple-jobs

###########################################################################
##      RESOURCES # types: pipelines | repositories | containers | packages
###########################################################################
resources:         
  repositories:
  - repository: DockerHubImagesRepo      
    type: GitHub
    endpoint: "wkreaGithub"
    name: wkrea/DockerHubImages
    # ref: 'refs/heads/master'  # ref name to use, defaults to 'refs/heads/master'

    # Inspired by
    # * https://github.com/microsoft/azure-pipelines-yaml/tree/master/design
    ###########################################################################
    ##                              TRIGGERS
    trigger:
      # https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md
      # https://dzone.com/articles/build-pipeline-triggers-using-azure-devopscicd
      batch: true
      branches:
        include:
        - refs/tags/{test}
        exclude:
        - '*'
      paths:
        exclude:
        - README.md
        - AzureTemplates/*
      tags:
        include:
        - v*
        exclude:
        - v2.0
    ###########################################################################
    ##                              PR's
    pr:
      autoCancel: true
      branches:
        include:
          - bug-fix/*
          - feat/*
          - azure_templates/*
        exclude:
          - master
          - releases/*
      paths:
        exclude:
        - README.md
        - AzureTemplates/*

  containers:
  - container: AlpineMini 
    endpoint: wallaskreaDockerHub
    image: wallaskrea/alpinemini:latest
    env: {}
    ports: "80"
    volumes: ""
    
stages:
  - template: AzureTemplates/DockerHub/BuildImages_jobs.yml #Build
    parameters:
      name: Build DockerHub Images
      pool:
        vmImage: 
          - ubuntu-latest
          - macOS-latest
          - windows-latest

  - stage: QA
    dependsOn: Build
    
  # - stage: Testing
  #   dependsOn: Build
  # - stage: Deploy
  #   dependsOn: 
  #   - QA
  #   - Testing

# ------------------------------------------------------------- OLD!!!

# resources:
# - repo: self

# pool:
#   vmImage: 'Ubuntu-18.04'

# steps:

# - task: Docker@2
#   displayName: Login to Docker Hub
#   inputs:
#     command: login
#     containerRegistry: wallaskreaDockerHub
# - task: Docker@2
#   displayName: Build and Push
#   inputs:
#     command: buildAndPush
#     repository: wallaskrea/alpinemini
#     Dockerfile: $(Build.SourcesDirectory)/Alpine/Dockerfile.AlpineMini
#     tags: |
#       10.3.1
#       latest
# - script: |
#     docker images 
# - task: Docker@2
#   displayName: Login to wkreaDockerHub
#   inputs:
#     containerRegistry: 'wallaskreaDockerHub'
#     command: 'login'