variables: # pipeline-level
  MY_VAR: "my value"
  ANOTHER_VAR: "another value"

stages:
  - template: AzureTemplates/DockerHub/BuildImages_jobs.yml
    parameters:
      name: Build DockerHub Images
