# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops

trigger:
  branches:
    include:
      - master
      - refs/tags/{tagname}
    exclude:
      - refs/tags/{othertagname}
# specific path build
pr:
  branches:
    include:
    - releases/*
    exclude:
    - master
  paths:
    include:
    - docs/*
    exclude:
    - docs/README.md

resources:
- repo: self

pool:
  vmImage: 'Ubuntu-18.04'

variables:
- name: imageName
  value: 'alpinemini:$(build.buildId)'

steps:

- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: wkreaDockerHub
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: wallaskrea/alpinemini
    Dockerfile: $(Build.SourcesDirectory)/Alpine/Dockerfile.AlpineMini
    tags: |
      10.3.1
      latest
- script: |
    docker images 
- task: Docker@2
  displayName: Login to wkreaDockerHub
  inputs:
    containerRegistry: 'wkreaDockerHub'
    command: 'login'