# Inspired by
# * https://github.com/microsoft/azure-pipelines-yaml/tree/master/design

###########################################################################
##                              TRIGGERS
###########################################################################
trigger:
  branches:
    include:
    - '*'
    exclude:
    - master
  paths:
    exclude:
    - README.md
  tags:
    include:
    - v*
    exclude:
    - v2.0
###########################################################################
##                              PR's
###########################################################################
pr:
  branches:
    include:
      - '*'
    exclude:
      - master
      - releases/*
  paths:
    exclude:
    - README.md

###########################################################################
##                              SCHEDULES
###########################################################################
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
    - releases/*
    exclude:
    - releases/ancient/*
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - releases/*
  always: true

###########################################################################
##      RESOURCES # types: pipelines | repositories | containers | packages
###########################################################################
resources:         

  repositories:
  - repository: DockerHubImagesRepo      
    type: GitHub
    connection: wkreGitHubConnection
    name: wkrea/DockerHubImages
    ref: 'refs/heads/master'  # ref name to use, defaults to 'refs/heads/master'

  containers:
  - container: AlpineMini 
    connection: wallaskreaDockerHub
    image: wallaskrea/alpinemini:latest
    env: {}
    ports: "80"
    volumes: ""

###########################################################################
##                              BUILD  STAGE
###########################################################################
stages:
  - stage: "Build DockerHub Images"
    jobs:
    - job: 'Testing'
      displayName: Testing
      strategy:
          matrix:
            AlpineMini:
              ImageName: "alpinemini"
              BuildContext: "$(Build.SourcesDirectory)/Alpine"
              Dockerfile: Dockerfile.alpinemini
              Tags: |
                  10.3.1
                  latest
            # CentOS7:
            #   container: "centos:7"
            # UbuntuPrecise:
            #   container: "ubuntu:precise"
            # UbuntuTrusty:
            #   container: "ubuntu:trusty"
            # UbuntuXenial:
            #   container: "ubuntu:xenial"
            # UbuntuBionic:
            #   container: "ubuntu:bionic"
            # DebianWheezy:
            #   container: "debian:wheezy"
            # DebianJessie:
            #   container: "debian:jessie"
            # DebianStretch:
            #   container: "debian:stretch"
            # DebianBuster:
            #   container: "debian:buster"
            # Manylinux1-686:
            #   container: "quay.io/pypa/manylinux1_i686:latest"
            # Manylinux1-64:
            #   container: "quay.io/pypa/manylinux1_x86_64:latest"
            # PhusionCentOS5-32:
            #   container: "phusion/centos-5-32:latest"
        # pool:
        #   vmImage: $(variables.container)
      steps:
      - script: echo hello
      - template: azure_templates/dockerhub_jobs.yml # Template reference
        parameters:
          job:
            name: "Building ${{ variables.ImageName }}"
            dockerfile: ${{ variables.Dockerfile }}
            buildContext: ${{ variables.BuildContext }}
            tags: ${{ variables.Tags }}


# https://github.com/alex/azure-pipelines-docker-test/blob/master/azure-pipelines.yml
# # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops

# trigger:
#   branches:
#     include:
#       - master
#       - refs/tags/{tagname}
#     exclude:
#       - refs/tags/{othertagname}
# # specific path build
# pr:
#   branches:
#     include:
#       - releases/*
#     exclude:
#       - master
#   paths:
#     include:
#       - docs/*
#     exclude:
#       - docs/README.md

# resources:
#   - repo: self

# pool:
#   vmImage: "Ubuntu-18.04"

# variables:
#   - name: imageName
#     value: "alpinemini:$(build.buildId)"

# steps:
#   - task: Docker@2
#     displayName: Login to Docker Hub
#     inputs:
#       command: login
#       containerRegistry: wkreaDockerHub
#   - task: Docker@2
#     displayName: Build and Push
#     inputs:
#       command: buildAndPush
#       repository: wallaskrea/alpinemini
#       Dockerfile: $(Build.SourcesDirectory)/Alpine/Dockerfile.AlpineMini
#       tags: |
#         10.3.1
#         latest
#   - task: Docker@2
#     displayName: Logout of wkreaDockerHub
#     inputs:
#       containerRegistry: "wkreaDockerHub"
#       command: "logout"
