# trigger:
# - master
trigger:
  branches:
    include:
      - refs/tags/{tagname}
    exclude:
      - refs/tags/{othertagname}
# specific path build
pr:
  branches:
    include:
    - releases/*
    exclude:
    - master
  paths:
    include:
    - docs/*
    exclude:
    - docs/README.md

resources:
- repo: self

pool:
  vmImage: 'Ubuntu-18.04'

variables:
- name: imageName
  value: 'alpinemini:$(build.buildId)'

steps:
- script: |
    docker build -f $(Build.SourcesDirectory)/Alpine/Dockerfile.alpinemini -t wallaskrea/$(imageName) .
    docker login -u DOCKER_HUB_USER -p $(DOCKER_HUB_PWD)
    docker tag wallaskrea/$(imageName) wallaskrea/$(imageName)
    docker push wallaskrea/$(imageName)
  displayName: 'docker build'