trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to wkreaDockerHub
      inputs:
        containerRegistry: 'wkreaDockerHub'
        command: 'login'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: wkreaDockerHub
        buildContext: '$(Build.SourcesDirectory)/Alpine'
        command: buildAndPush
        repository: test
        Dockerfile: '$(Build.SourcesDirectory)/Alpine/Dockerfile.AlpineGLIB'
        imageName: $(containerRegistry)/Alpine$(Build.Repository.Name)
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Logout of wkreaDockerHub
      inputs:
        containerRegistry: 'wkreaDockerHub'
        command: 'logout'

