variables:
  DOCKER_USERNAME: wallaskrea
  DOCKER_PASSWORD: wallas2011
  IMAGE_NAME: alpine_

stages:
- stage: "Build DockerHub Images"
  jobs:
  - job: "docker"
    strategy:
      matrix:
        amd64-alpine:
          IMAGE_SUFF: GLIB
          IMAGE_TAG: 10.3.1
        amd64-alpine-glibc:
          IMAGE_SUFF: miniGLIB
          IMAGE_TAG: 10.3.1
        amd64-alpine-glibc-miniconda:
          IMAGE_TAG: minicondaGLIB
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - script: |
        cd dockeragent
        docker build -f Dockerfile.$(IMAGE_TAG) -t $(DOCKER_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG) . 
      displayName: 'docker build'
    - script: |
        docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
      displayName: 'docker login'
    - script: |
        docker push $(DOCKER_USERNAME)/$(IMAGE_NAME)
      displayName: 'docker push'
      #condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')