trigger:
  branches:
    include:
    -  master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Docker@2
  displayName: Docker build and Push
  inputs:
    dockerfile: Alpine/Dockerfile.AlpineGLIB
    command: buildAndPush
    repository: DockerHubImages
    tags: |
      $(Build.BuildNumber)
      latest
