trigger:
- master

resources:
- repo: self

variables:
  DOCKER_USERNAME: wallaskrea
  DOCKER_PASSWORD: wallas2011
  IMAGE_NAME: 'alpine'
  tag: '$(Build.BuildId)'

stages:
- stage: "Build DockerHub Images"
  jobs:
  - job: "docker"
    strategy:
      matrix:
        amd64-alpine:
          IMAGE_SUFF: glib
          IMAGE_TAG: 10.3.1
        amd64-alpine-glibc:
          IMAGE_SUFF: miniglib
          IMAGE_TAG: 10.3.1
        amd64-alpine-glibc-miniconda:
          IMAGE_TAG: minicondaglib
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - script: |
        docker build -f Dockerfile.$(IMAGE_TAG) -t $(DOCKER_USERNAME)/$(IMAGE_NAME)$(IMAGE_SUFF):$(IMAGE_TAG) . 
      displayName: 'docker build'
    - script: |
        docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
      displayName: 'docker login'
    - script: |
        docker push $(DOCKER_USERNAME)/$(IMAGE_NAME)$(IMAGE_SUFF)
      displayName: 'docker push'
      #condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')