# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
parameters:
  tareas: { }
variables:
- template: azure_templates/jobs_variables.yml  # Template reference
jobs:
  - ${{ each job in parameters.tareas }}: # Each job
      - job: ${{ job.job }} # Copy the job properties
        displayName: ${{ job.name }}
        condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
        # - ${{ if job.dependsOn }}:
        #   - ${{ job.dependsOn }}
        workspace:
          clean: all # outputs | resources | all what to clean up before the job runs 
        container: "" # container to run this job inside
        timeoutInMinutes: ${{ variables.TIMEOUT }} # how long to run the job before automatically cancelling
        cancelTimeoutInMinutes: ${{ variables.CANCELTIMEOUT }} # how much time to give 'run always even if cancelled tasks' before killing them

        - ${{ each vmImage in ${{ variables.vmImages }} }}: # Each job
          pool:
            vmImage: $(vmImage)
          steps:
            - script: echo $(vmImage)-> building ${{ job.name }}
            - template: azure_templates/buildDockerHubImages.yml # Template build&push dockerhub
              param:
                serviceDockerHub: ${{ variables.SERVICENAME_DOCKERHUB }}
                repository: ${{ variables.DOCKERHUB_ACCOUNT }}/${{ job.ImageName }} #wallaskrea/alpinemini # 
                dockerfile: ${{ job.dockerfile }}
                buildContext: ${{ job.buildContext }} #$(ALPINE_CONTEXT)
                tags: ${{ job.tags }}
            - script: echo $(vmImage) -> finish ${{ job.name }}