# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml
parameters:
  name: ""
  serviceDockerHub: ""

stages:
  - stage: Build
    displayName: Build for
    jobs:
      - job: Linux
        pool:
          vmImage: "ubuntu-16.04"
        workspace:
          clean: all # outputs | resources | all what to clean up before the job runs
        timeoutInMinutes: 30 # how long to run the job before automatically cancelling
        cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before killing them

        strategy:
          matrix:
            AlpineMini:
              ImageName: "alpinemini"
              RepositoryName: wallaskrea
              BuildContext: ./Alpine
              Tags: |
                10.3.1
                latest
            AlpineMiniGLIB:
              ImageName: "alpineminiglib"
              RepositoryName: wallaskrea
              BuildContext: Alpine
              Tags: |
                10.3.1
                latest
        steps:
          - script: echo hello from Linux $(ImageName) $(ImageName)
          - template: BuildImages_steps.yml # Template reference
            parameters:
              ImageName: $(ImageName)
              repoName: $(RepositoryName)
              serviceDockerHub: $(parameters.serviceDockerHub)
              buildContext: $(BuildContext)
              tags: $(Tags)
      # - job: Windows
      #   pool:
      #     vmImage: "vs2017-win2016"
      #   steps:
      #     - script: echo hello from Windows
      # - job: macOS
      #   pool:
      #     vmImage: "macOS-10.13"
      #   steps:
      #     - script: echo hello from macOS
