parameters:
  name: ""
  os: ""

stages:
  - stage: Build
    displayName: Build for
    jobs:
      - job: Linux
        pool:
          vmImage: "ubuntu-16.04"
        strategy:
          matrix:
            AlpineMini:
              ImageName: "alpinemini"
              BuildContext: "$(Build.SourcesDirectory)/Alpine"
              Dockerfile: Dockerfile.alpinemini
              Tags: |
                10.3.1
                latest
            AlpineMiniGLIB:
              ImageName: "alpineminiglib"
              BuildContext: "$(Build.SourcesDirectory)/Alpine"
              Dockerfile: Dockerfile.alpineminiglib
              Tags: |
                10.3.1
                latest
        steps:
          - script: echo hello from Linux $(variables.ImageName) ${{ variables.ImageName }}
          - template: azure_templates/dockerhub_jobs.yml # Template reference
            parameters:
              tarea:
                name: "Building ${{ variables.ImageName }}"
                dockerfile: ${{ variables.Dockerfile }}
                buildContext: ${{ variables.BuildContext }}
                tags: ${{ variables.Tags }}
      - job: Windows
        pool:
          vmImage: "vs2017-win2016"
        steps:
          - script: echo hello from Windows
      - job: macOS
        pool:
          vmImage: "macOS-10.13"
        steps:
          - script: echo hello from macOS
