parameters:
  name: ""
  os: ""

stages:
  - stage: Build
    displayName: Build for ${{ parameters.name }}
    jobs:
      - job: ${{ parameters.name }}_Windows
        # pool:
        #   vmImage: variables.vm #vs2017-win2016
        strategy:
          matrix:
            Win:
              vmImage: "vs2017-win2016"
            Lin:
              vmImage: "ubuntu-16.04"
            Mac:
              vmImage: "macos-10.13"
        steps:
          - ${{ if eq($vmImage, 'ubuntu-16.04') }}:
              - script: echo $(vmImage)
          - ${{ else }}:
              - script: dir
      # - job: ${{ parameters.name }}_Linux
      #   pool:
      #     vmImage: ubuntu-16.04
      #   steps:
      #     - script: npm install
      #     - script: npm test -- --file=${{ parameters.testFile }}
      # - job: ${{ parameters.name }}_Mac
      #   pool:
      #     vmImage: macos-10.13
      #   steps:
      #     - script: npm install
      #     - script: npm test -- --file=${{ parameters.testFile }}
