parameters:
  name: ""
  os: ""

stages:
  - stage: Build
    displayName: Build for ${{ parameters.name }}
    jobs:
      - job: Windows
        pool:
          vmImage: "vs2017-win2016"
        strategy:
          matrix:
            AlpineMini:
              ImageName: "alpinemini"
              BuildContext: "$(Build.SourcesDirectory)/Alpine"
              Dockerfile: Dockerfile.alpinemini
              Tags: |
                10.3.1
                latest
            AlpineMiniGLIB:
              ImageName: "alpineminiglib"
              BuildContext: "$(Build.SourcesDirectory)/Alpine"
              Dockerfile: Dockerfile.alpineminiglib
              Tags: |
                10.3.1
                latest
        steps:
          - script: echo hello from Windows
      - job: macOS
        pool:
          vmImage: "macOS-10.13"
        steps:
          - script: echo hello from macOS
      - job: Linux
        pool:
          vmImage: "ubuntu-16.04"
        steps:
          - script: echo hello from Linux
